---
  - name: Permissions
    hosts: localhost
    tasks:
      - name: add files
        file:
          path: /root/test_config1
          state: touch
          mode: u=rw,g=rw,o=r
      - name: 
        file:
          path: /root/test_config2
          state: touch
          mode: u=rw,g=rw,o=r
      - name:
        file:
          path: /root/test_config3
          state: touch
          mode: u=rw,g=rw,o=r


          